TRUNCATE TABLE countries;

INSERT INTO countries (id, name, code, flag, created_at, updated_at) VALUES
(1, 'Afghanistan', 'AFG', 'https://restcountries.eu/data/afg.svg', NULL, NULL),
(2, 'Åland Islands', 'ALA', 'https://restcountries.eu/data/ala.svg', NULL, NULL),
(3, 'Albania', 'ALB', 'https://restcountries.eu/data/alb.svg', NULL, NULL),
(4, 'Algeria', 'DZA', 'https://restcountries.eu/data/dza.svg', NULL, NULL),
(5, 'American Samoa', 'ASM', 'https://restcountries.eu/data/asm.svg', NULL, NULL),
(6, 'Andorra', 'AND', 'https://restcountries.eu/data/and.svg', NULL, NULL),
(7, 'Angola', 'AGO', 'https://restcountries.eu/data/ago.svg', NULL, NULL),
(8, 'Anguilla', 'AIA', 'https://restcountries.eu/data/aia.svg', NULL, NULL),
(9, 'Antarctica', 'ATA', 'https://restcountries.eu/data/ata.svg', NULL, NULL),
(10, 'Antigua and Barbuda', 'ATG', 'https://restcountries.eu/data/atg.svg', NULL, NULL),
(11, 'Argentina', 'ARG', 'https://restcountries.eu/data/arg.svg', NULL, NULL),
(12, 'Armenia', 'ARM', 'https://restcountries.eu/data/arm.svg', NULL, NULL),
(13, 'Aruba', 'ABW', 'https://restcountries.eu/data/abw.svg', NULL, NULL),
(14, 'Australia', 'AUS', 'https://restcountries.eu/data/aus.svg', NULL, NULL),
(15, 'Austria', 'AUT', 'https://restcountries.eu/data/aut.svg', NULL, NULL),
(16, 'Azerbaijan', 'AZE', 'https://restcountries.eu/data/aze.svg', NULL, NULL),
(17, 'Bahamas', 'BHS', 'https://restcountries.eu/data/bhs.svg', NULL, NULL),
(18, 'Bahrain', 'BHR', 'https://restcountries.eu/data/bhr.svg', NULL, NULL),
(19, 'Bangladesh', 'BGD', 'https://restcountries.eu/data/bgd.svg', NULL, NULL),
(20, 'Barbados', 'BRB', 'https://restcountries.eu/data/brb.svg', NULL, NULL),
(21, 'Belarus', 'BLR', 'https://restcountries.eu/data/blr.svg', NULL, NULL),
(22, 'Belgium', 'BEL', 'https://restcountries.eu/data/bel.svg', NULL, NULL),
(23, 'Belize', 'BLZ', 'https://restcountries.eu/data/blz.svg', NULL, NULL),
(24, 'Benin', 'BEN', 'https://restcountries.eu/data/ben.svg', NULL, NULL),
(25, 'Bermuda', 'BMU', 'https://restcountries.eu/data/bmu.svg', NULL, NULL),
(26, 'Bhutan', 'BTN', 'https://restcountries.eu/data/btn.svg', NULL, NULL),
(27, 'Bolivia (Plurinational State of)', 'BOL', 'https://restcountries.eu/data/bol.svg', NULL, NULL),
(28, 'Bonaire, Sint Eustatius and Saba', 'BES', 'https://restcountries.eu/data/bes.svg', NULL, NULL),
(29, 'Bosnia and Herzegovina', 'BIH', 'https://restcountries.eu/data/bih.svg', NULL, NULL),
(30, 'Botswana', 'BWA', 'https://restcountries.eu/data/bwa.svg', NULL, NULL),
(31, 'Bouvet Island', 'BVT', 'https://restcountries.eu/data/bvt.svg', NULL, NULL),
(32, 'Brazil', 'BRA', 'https://restcountries.eu/data/bra.svg', NULL, NULL),
(33, 'British Indian Ocean Territory', 'IOT', 'https://restcountries.eu/data/iot.svg', NULL, NULL),
(34, 'United States Minor Outlying Islands', 'UMI', 'https://restcountries.eu/data/umi.svg', NULL, NULL),
(35, 'Virgin Islands (British)', 'VGB', 'https://restcountries.eu/data/vgb.svg', NULL, NULL),
(36, 'Virgin Islands (U.S.)', 'VIR', 'https://restcountries.eu/data/vir.svg', NULL, NULL),
(37, 'Brunei Darussalam', 'BRN', 'https://restcountries.eu/data/brn.svg', NULL, NULL),
(38, 'Bulgaria', 'BGR', 'https://restcountries.eu/data/bgr.svg', NULL, NULL),
(39, 'Burkina Faso', 'BFA', 'https://restcountries.eu/data/bfa.svg', NULL, NULL),
(40, 'Burundi', 'BDI', 'https://restcountries.eu/data/bdi.svg', NULL, NULL),
(41, 'Cambodia', 'KHM', 'https://restcountries.eu/data/khm.svg', NULL, NULL),
(42, 'Cameroon', 'CMR', 'https://restcountries.eu/data/cmr.svg', NULL, NULL),
(43, 'Canada', 'CAN', 'https://restcountries.eu/data/can.svg', NULL, NULL),
(44, 'Cabo Verde', 'CPV', 'https://restcountries.eu/data/cpv.svg', NULL, NULL),
(45, 'Cayman Islands', 'CYM', 'https://restcountries.eu/data/cym.svg', NULL, NULL),
(46, 'Central African Republic', 'CAF', 'https://restcountries.eu/data/caf.svg', NULL, NULL),
(47, 'Chad', 'TCD', 'https://restcountries.eu/data/tcd.svg', NULL, NULL),
(48, 'Chile', 'CHL', 'https://restcountries.eu/data/chl.svg', NULL, NULL),
(49, 'China', 'CHN', 'https://restcountries.eu/data/chn.svg', NULL, NULL),
(50, 'Christmas Island', 'CXR', 'https://restcountries.eu/data/cxr.svg', NULL, NULL),
(51, 'Cocos (Keeling) Islands', 'CCK', 'https://restcountries.eu/data/cck.svg', NULL, NULL),
(52, 'Colombia', 'COL', 'https://restcountries.eu/data/col.svg', NULL, NULL),
(53, 'Comoros', 'COM', 'https://restcountries.eu/data/com.svg', NULL, NULL),
(54, 'Congo', 'COG', 'https://restcountries.eu/data/cog.svg', NULL, NULL),
(55, 'Congo (Democratic Republic of the)', 'COD', 'https://restcountries.eu/data/cod.svg', NULL, NULL),
(56, 'Cook Islands', 'COK', 'https://restcountries.eu/data/cok.svg', NULL, NULL),
(57, 'Costa Rica', 'CRI', 'https://restcountries.eu/data/cri.svg', NULL, NULL),
(58, 'Croatia', 'HRV', 'https://restcountries.eu/data/hrv.svg', NULL, NULL),
(59, 'Cuba', 'CUB', 'https://restcountries.eu/data/cub.svg', NULL, NULL),
(60, 'Curaçao', 'CUW', 'https://restcountries.eu/data/cuw.svg', NULL, NULL),
(61, 'Cyprus', 'CYP', 'https://restcountries.eu/data/cyp.svg', NULL, NULL),
(62, 'Czech Republic', 'CZE', 'https://restcountries.eu/data/cze.svg', NULL, NULL),
(63, 'Denmark', 'DNK', 'https://restcountries.eu/data/dnk.svg', NULL, NULL),
(64, 'Djibouti', 'DJI', 'https://restcountries.eu/data/dji.svg', NULL, NULL),
(65, 'Dominica', 'DMA', 'https://restcountries.eu/data/dma.svg', NULL, NULL),
(66, 'Dominican Republic', 'DOM', 'https://restcountries.eu/data/dom.svg', NULL, NULL),
(67, 'Ecuador', 'ECU', 'https://restcountries.eu/data/ecu.svg', NULL, NULL),
(68, 'Egypt', 'EGY', 'https://restcountries.eu/data/egy.svg', NULL, NULL),
(69, 'El Salvador', 'SLV', 'https://restcountries.eu/data/slv.svg', NULL, NULL),
(70, 'Equatorial Guinea', 'GNQ', 'https://restcountries.eu/data/gnq.svg', NULL, NULL),
(71, 'Eritrea', 'ERI', 'https://restcountries.eu/data/eri.svg', NULL, NULL),
(72, 'Estonia', 'EST', 'https://restcountries.eu/data/est.svg', NULL, NULL),
(73, 'Ethiopia', 'ETH', 'https://restcountries.eu/data/eth.svg', NULL, NULL),
(74, 'Falkland Islands (Malvinas)', 'FLK', 'https://restcountries.eu/data/flk.svg', NULL, NULL),
(75, 'Faroe Islands', 'FRO', 'https://restcountries.eu/data/fro.svg', NULL, NULL),
(76, 'Fiji', 'FJI', 'https://restcountries.eu/data/fji.svg', NULL, NULL),
(77, 'Finland', 'FIN', 'https://restcountries.eu/data/fin.svg', NULL, NULL),
(78, 'France', 'FRA', 'https://restcountries.eu/data/fra.svg', NULL, NULL),
(79, 'French Guiana', 'GUF', 'https://restcountries.eu/data/guf.svg', NULL, NULL),
(80, 'French Polynesia', 'PYF', 'https://restcountries.eu/data/pyf.svg', NULL, NULL),
(81, 'French Southern Territories', 'ATF', 'https://restcountries.eu/data/atf.svg', NULL, NULL),
(82, 'Gabon', 'GAB', 'https://restcountries.eu/data/gab.svg', NULL, NULL),
(83, 'Gambia', 'GMB', 'https://restcountries.eu/data/gmb.svg', NULL, NULL),
(84, 'Georgia', 'GEO', 'https://restcountries.eu/data/geo.svg', NULL, NULL),
(85, 'Germany', 'DEU', 'https://restcountries.eu/data/deu.svg', NULL, NULL),
(86, 'Ghana', 'GHA', 'https://restcountries.eu/data/gha.svg', NULL, NULL),
(87, 'Gibraltar', 'GIB', 'https://restcountries.eu/data/gib.svg', NULL, NULL),
(88, 'Greece', 'GRC', 'https://restcountries.eu/data/grc.svg', NULL, NULL),
(89, 'Greenland', 'GRL', 'https://restcountries.eu/data/grl.svg', NULL, NULL),
(90, 'Grenada', 'GRD', 'https://restcountries.eu/data/grd.svg', NULL, NULL),
(91, 'Guadeloupe', 'GLP', 'https://restcountries.eu/data/glp.svg', NULL, NULL),
(92, 'Guam', 'GUM', 'https://restcountries.eu/data/gum.svg', NULL, NULL),
(93, 'Guatemala', 'GTM', 'https://restcountries.eu/data/gtm.svg', NULL, NULL),
(94, 'Guernsey', 'GGY', 'https://restcountries.eu/data/ggy.svg', NULL, NULL),
(95, 'Guinea', 'GIN', 'https://restcountries.eu/data/gin.svg', NULL, NULL),
(96, 'Guinea-Bissau', 'GNB', 'https://restcountries.eu/data/gnb.svg', NULL, NULL),
(97, 'Guyana', 'GUY', 'https://restcountries.eu/data/guy.svg', NULL, NULL),
(98, 'Haiti', 'HTI', 'https://restcountries.eu/data/hti.svg', NULL, NULL),
(99, 'Heard Island and McDonald Islands', 'HMD', 'https://restcountries.eu/data/hmd.svg', NULL, NULL),
(100, 'Holy See', 'VAT', 'https://restcountries.eu/data/vat.svg', NULL, NULL),
(101, 'Honduras', 'HND', 'https://restcountries.eu/data/hnd.svg', NULL, NULL),
(102, 'Hong Kong', 'HKG', 'https://restcountries.eu/data/hkg.svg', NULL, NULL),
(103, 'Hungary', 'HUN', 'https://restcountries.eu/data/hun.svg', NULL, NULL),
(104, 'Iceland', 'ISL', 'https://restcountries.eu/data/isl.svg', NULL, NULL),
(105, 'India', 'IND', 'https://restcountries.eu/data/ind.svg', NULL, NULL),
(106, 'Indonesia', 'IDN', 'https://restcountries.eu/data/idn.svg', NULL, NULL),
(107, 'Côte dIvoire', 'CIV', 'https://restcountries.eu/data/civ.svg', NULL, NULL),
(108, 'Iran (Islamic Republic of)', 'IRN', 'https://restcountries.eu/data/irn.svg', NULL, NULL),
(109, 'Iraq', 'IRQ', 'https://restcountries.eu/data/irq.svg', NULL, NULL),
(110, 'Ireland', 'IRL', 'https://restcountries.eu/data/irl.svg', NULL, NULL),
(111, 'Isle of Man', 'IMN', 'https://restcountries.eu/data/imn.svg', NULL, NULL),
(112, 'Italy', 'ITA', 'https://restcountries.eu/data/ita.svg', NULL, NULL),
(113, 'Jamaica', 'JAM', 'https://restcountries.eu/data/jam.svg', NULL, NULL),
(114, 'Japan', 'JPN', 'https://restcountries.eu/data/jpn.svg', NULL, NULL),
(115, 'Jersey', 'JEY', 'https://restcountries.eu/data/jey.svg', NULL, NULL),
(116, 'Jordan', 'JOR', 'https://restcountries.eu/data/jor.svg', NULL, NULL),
(117, 'Kazakhstan', 'KAZ', 'https://restcountries.eu/data/kaz.svg', NULL, NULL),
(118, 'Kenya', 'KEN', 'https://restcountries.eu/data/ken.svg', NULL, NULL),
(119, 'Kiribati', 'KIR', 'https://restcountries.eu/data/kir.svg', NULL, NULL),
(120, 'Kuwait', 'KWT', 'https://restcountries.eu/data/kwt.svg', NULL, NULL),
(121, 'Kyrgyzstan', 'KGZ', 'https://restcountries.eu/data/kgz.svg', NULL, NULL),
(122, 'Lao Peoples Democratic Republic', 'LAO', 'https://restcountries.eu/data/lao.svg', NULL, NULL),
(123, 'Latvia', 'LVA', 'https://restcountries.eu/data/lva.svg', NULL, NULL),
(124, 'Lebanon', 'LBN', 'https://restcountries.eu/data/lbn.svg', NULL, NULL),
(125, 'Lesotho', 'LSO', 'https://restcountries.eu/data/lso.svg', NULL, NULL),
(126, 'Liberia', 'LBR', 'https://restcountries.eu/data/lbr.svg', NULL, NULL),
(127, 'Libya', 'LBY', 'https://restcountries.eu/data/lby.svg', NULL, NULL),
(128, 'Liechtenstein', 'LIE', 'https://restcountries.eu/data/lie.svg', NULL, NULL),
(129, 'Lithuania', 'LTU', 'https://restcountries.eu/data/ltu.svg', NULL, NULL),
(130, 'Luxembourg', 'LUX', 'https://restcountries.eu/data/lux.svg', NULL, NULL),
(131, 'Macao', 'MAC', 'https://restcountries.eu/data/mac.svg', NULL, NULL),
(132, 'Macedonia (the former Yugoslav Republic of)', 'MKD', 'https://restcountries.eu/data/mkd.svg', NULL, NULL),
(133, 'Madagascar', 'MDG', 'https://restcountries.eu/data/mdg.svg', NULL, NULL),
(134, 'Malawi', 'MWI', 'https://restcountries.eu/data/mwi.svg', NULL, NULL),
(135, 'Malaysia', 'MYS', 'https://restcountries.eu/data/mys.svg', NULL, NULL),
(136, 'Maldives', 'MDV', 'https://restcountries.eu/data/mdv.svg', NULL, NULL),
(137, 'Mali', 'MLI', 'https://restcountries.eu/data/mli.svg', NULL, NULL),
(138, 'Malta', 'MLT', 'https://restcountries.eu/data/mlt.svg', NULL, NULL),
(139, 'Marshall Islands', 'MHL', 'https://restcountries.eu/data/mhl.svg', NULL, NULL),
(140, 'Martinique', 'MTQ', 'https://restcountries.eu/data/mtq.svg', NULL, NULL),
(141, 'Mauritania', 'MRT', 'https://restcountries.eu/data/mrt.svg', NULL, NULL),
(142, 'Mauritius', 'MUS', 'https://restcountries.eu/data/mus.svg', NULL, NULL),
(143, 'Mayotte', 'MYT', 'https://restcountries.eu/data/myt.svg', NULL, NULL),
(144, 'Mexico', 'MEX', 'https://restcountries.eu/data/mex.svg', NULL, NULL),
(145, 'Micronesia (Federated States of)', 'FSM', 'https://restcountries.eu/data/fsm.svg', NULL, NULL),
(146, 'Moldova (Republic of)', 'MDA', 'https://restcountries.eu/data/mda.svg', NULL, NULL),
(147, 'Monaco', 'MCO', 'https://restcountries.eu/data/mco.svg', NULL, NULL),
(148, 'Mongolia', 'MNG', 'https://restcountries.eu/data/mng.svg', NULL, NULL),
(149, 'Montenegro', 'MNE', 'https://restcountries.eu/data/mne.svg', NULL, NULL),
(150, 'Montserrat', 'MSR', 'https://restcountries.eu/data/msr.svg', NULL, NULL),
(151, 'Morocco', 'MAR', 'https://restcountries.eu/data/mar.svg', NULL, NULL),
(152, 'Mozambique', 'MOZ', 'https://restcountries.eu/data/moz.svg', NULL, NULL),
(153, 'Myanmar', 'MMR', 'https://restcountries.eu/data/mmr.svg', NULL, NULL),
(154, 'Namibia', 'NAM', 'https://restcountries.eu/data/nam.svg', NULL, NULL),
(155, 'Nauru', 'NRU', 'https://restcountries.eu/data/nru.svg', NULL, NULL),
(156, 'Nepal', 'NPL', 'https://restcountries.eu/data/npl.svg', NULL, NULL),
(157, 'Netherlands', 'NLD', 'https://restcountries.eu/data/nld.svg', NULL, NULL),
(158, 'New Caledonia', 'NCL', 'https://restcountries.eu/data/ncl.svg', NULL, NULL),
(159, 'New Zealand', 'NZL', 'https://restcountries.eu/data/nzl.svg', NULL, NULL),
(160, 'Nicaragua', 'NIC', 'https://restcountries.eu/data/nic.svg', NULL, NULL),
(161, 'Niger', 'NER', 'https://restcountries.eu/data/ner.svg', NULL, NULL),
(162, 'Nigeria', 'NGA', 'https://restcountries.eu/data/nga.svg', NULL, NULL),
(163, 'Niue', 'NIU', 'https://restcountries.eu/data/niu.svg', NULL, NULL),
(164, 'Norfolk Island', 'NFK', 'https://restcountries.eu/data/nfk.svg', NULL, NULL),
(165, 'Korea (Democratic Peoples Republic of)', 'PRK', 'https://restcountries.eu/data/prk.svg', NULL, NULL),
(166, 'Northern Mariana Islands', 'MNP', 'https://restcountries.eu/data/mnp.svg', NULL, NULL),
(167, 'Norway', 'NOR', 'https://restcountries.eu/data/nor.svg', NULL, NULL),
(168, 'Oman', 'OMN', 'https://restcountries.eu/data/omn.svg', NULL, NULL),
(169, 'Pakistan', 'PAK', 'https://restcountries.eu/data/pak.svg', NULL, NULL),
(170, 'Palau', 'PLW', 'https://restcountries.eu/data/plw.svg', NULL, NULL),
(171, 'Palestine, State of', 'PSE', 'https://restcountries.eu/data/pse.svg', NULL, NULL),
(172, 'Panama', 'PAN', 'https://restcountries.eu/data/pan.svg', NULL, NULL),
(173, 'Papua New Guinea', 'PNG', 'https://restcountries.eu/data/png.svg', NULL, NULL),
(174, 'Paraguay', 'PRY', 'https://restcountries.eu/data/pry.svg', NULL, NULL),
(175, 'Peru', 'PER', 'https://restcountries.eu/data/per.svg', NULL, NULL),
(176, 'Philippines', 'PHL', 'https://restcountries.eu/data/phl.svg', NULL, NULL),
(177, 'Pitcairn', 'PCN', 'https://restcountries.eu/data/pcn.svg', NULL, NULL),
(178, 'Poland', 'POL', 'https://restcountries.eu/data/pol.svg', NULL, NULL),
(179, 'Portugal', 'PRT', 'https://restcountries.eu/data/prt.svg', NULL, NULL),
(180, 'Puerto Rico', 'PRI', 'https://restcountries.eu/data/pri.svg', NULL, NULL),
(181, 'Qatar', 'QAT', 'https://restcountries.eu/data/qat.svg', NULL, NULL),
(182, 'Republic of Kosovo', 'KOS', 'https://restcountries.eu/data/kos.svg', NULL, NULL),
(183, 'Réunion', 'REU', 'https://restcountries.eu/data/reu.svg', NULL, NULL),
(184, 'Romania', 'ROU', 'https://restcountries.eu/data/rou.svg', NULL, NULL),
(185, 'Russian Federation', 'RUS', 'https://restcountries.eu/data/rus.svg', NULL, NULL),
(186, 'Rwanda', 'RWA', 'https://restcountries.eu/data/rwa.svg', NULL, NULL),
(187, 'Saint Barthélemy', 'BLM', 'https://restcountries.eu/data/blm.svg', NULL, NULL),
(188, 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'https://restcountries.eu/data/shn.svg', NULL, NULL),
(189, 'Saint Kitts and Nevis', 'KNA', 'https://restcountries.eu/data/kna.svg', NULL, NULL),
(190, 'Saint Lucia', 'LCA', 'https://restcountries.eu/data/lca.svg', NULL, NULL),
(191, 'Saint Martin (French part)', 'MAF', 'https://restcountries.eu/data/maf.svg', NULL, NULL),
(192, 'Saint Pierre and Miquelon', 'SPM', 'https://restcountries.eu/data/spm.svg', NULL, NULL),
(193, 'Saint Vincent and the Grenadines', 'VCT', 'https://restcountries.eu/data/vct.svg', NULL, NULL),
(194, 'Samoa', 'WSM', 'https://restcountries.eu/data/wsm.svg', NULL, NULL),
(195, 'San Marino', 'SMR', 'https://restcountries.eu/data/smr.svg', NULL, NULL),
(196, 'Sao Tome and Principe', 'STP', 'https://restcountries.eu/data/stp.svg', NULL, NULL),
(197, 'Saudi Arabia', 'SAU', 'https://restcountries.eu/data/sau.svg', NULL, NULL),
(198, 'Senegal', 'SEN', 'https://restcountries.eu/data/sen.svg', NULL, NULL),
(199, 'Serbia', 'SRB', 'https://restcountries.eu/data/srb.svg', NULL, NULL),
(200, 'Seychelles', 'SYC', 'https://restcountries.eu/data/syc.svg', NULL, NULL),
(201, 'Sierra Leone', 'SLE', 'https://restcountries.eu/data/sle.svg', NULL, NULL),
(202, 'Singapore', 'SGP', 'https://restcountries.eu/data/sgp.svg', NULL, NULL),
(203, 'Sint Maarten (Dutch part)', 'SXM', 'https://restcountries.eu/data/sxm.svg', NULL, NULL),
(204, 'Slovakia', 'SVK', 'https://restcountries.eu/data/svk.svg', NULL, NULL),
(205, 'Slovenia', 'SVN', 'https://restcountries.eu/data/svn.svg', NULL, NULL),
(206, 'Solomon Islands', 'SLB', 'https://restcountries.eu/data/slb.svg', NULL, NULL),
(207, 'Somalia', 'SOM', 'https://restcountries.eu/data/som.svg', NULL, NULL),
(208, 'South Africa', 'ZAF', 'https://restcountries.eu/data/zaf.svg', NULL, NULL),
(209, 'South Georgia and the South Sandwich Islands', 'SGS', 'https://restcountries.eu/data/sgs.svg', NULL, NULL),
(210, 'Korea (Republic of)', 'KOR', 'https://restcountries.eu/data/kor.svg', NULL, NULL),
(211, 'South Sudan', 'SSD', 'https://restcountries.eu/data/ssd.svg', NULL, NULL),
(212, 'Spain', 'ESP', 'https://restcountries.eu/data/esp.svg', NULL, NULL),
(213, 'Sri Lanka', 'LKA', 'https://restcountries.eu/data/lka.svg', NULL, NULL),
(214, 'Sudan', 'SDN', 'https://restcountries.eu/data/sdn.svg', NULL, NULL),
(215, 'Suriname', 'SUR', 'https://restcountries.eu/data/sur.svg', NULL, NULL),
(216, 'Svalbard and Jan Mayen', 'SJM', 'https://restcountries.eu/data/sjm.svg', NULL, NULL),
(217, 'Swaziland', 'SWZ', 'https://restcountries.eu/data/swz.svg', NULL, NULL),
(218, 'Sweden', 'SWE', 'https://restcountries.eu/data/swe.svg', NULL, NULL),
(219, 'Switzerland', 'CHE', 'https://restcountries.eu/data/che.svg', NULL, NULL),
(220, 'Syrian Arab Republic', 'SYR', 'https://restcountries.eu/data/syr.svg', NULL, NULL),
(221, 'Taiwan', 'TWN', 'https://restcountries.eu/data/twn.svg', NULL, NULL),
(222, 'Tajikistan', 'TJK', 'https://restcountries.eu/data/tjk.svg', NULL, NULL),
(223, 'Tanzania, United Republic of', 'TZA', 'https://restcountries.eu/data/tza.svg', NULL, NULL),
(224, 'Thailand', 'THA', 'https://restcountries.eu/data/tha.svg', NULL, NULL),
(225, 'Timor-Leste', 'TLS', 'https://restcountries.eu/data/tls.svg', NULL, NULL),
(226, 'Togo', 'TGO', 'https://restcountries.eu/data/tgo.svg', NULL, NULL),
(227, 'Tokelau', 'TKL', 'https://restcountries.eu/data/tkl.svg', NULL, NULL),
(228, 'Tonga', 'TON', 'https://restcountries.eu/data/ton.svg', NULL, NULL),
(229, 'Trinidad and Tobago', 'TTO', 'https://restcountries.eu/data/tto.svg', NULL, NULL),
(230, 'Tunisia', 'TUN', 'https://restcountries.eu/data/tun.svg', NULL, NULL),
(231, 'Turkey', 'TUR', 'https://restcountries.eu/data/tur.svg', NULL, NULL),
(232, 'Turkmenistan', 'TKM', 'https://restcountries.eu/data/tkm.svg', NULL, NULL),
(233, 'Turks and Caicos Islands', 'TCA', 'https://restcountries.eu/data/tca.svg', NULL, NULL),
(234, 'Tuvalu', 'TUV', 'https://restcountries.eu/data/tuv.svg', NULL, NULL),
(235, 'Uganda', 'UGA', 'https://restcountries.eu/data/uga.svg', NULL, NULL),
(236, 'Ukraine', 'UKR', 'https://restcountries.eu/data/ukr.svg', NULL, NULL),
(237, 'United Arab Emirates', 'ARE', 'https://restcountries.eu/data/are.svg', NULL, NULL),
(238, 'United Kingdom of Great Britain and Northern Ireland', 'GBR', 'https://restcountries.eu/data/gbr.svg', NULL, NULL),
(239, 'United States of America', 'USA', 'https://restcountries.eu/data/usa.svg', NULL, NULL),
(240, 'Uruguay', 'URY', 'https://restcountries.eu/data/ury.svg', NULL, NULL),
(241, 'Uzbekistan', 'UZB', 'https://restcountries.eu/data/uzb.svg', NULL, NULL),
(242, 'Vanuatu', 'VUT', 'https://restcountries.eu/data/vut.svg', NULL, NULL),
(243, 'Venezuela (Bolivarian Republic of)', 'VEN', 'https://restcountries.eu/data/ven.svg', NULL, NULL),
(244, 'Viet Nam', 'VNM', 'https://restcountries.eu/data/vnm.svg', NULL, NULL),
(245, 'Wallis and Futuna', 'WLF', 'https://restcountries.eu/data/wlf.svg', NULL, NULL),
(246, 'Western Sahara', 'ESH', 'https://restcountries.eu/data/esh.svg', NULL, NULL),
(247, 'Yemen', 'YEM', 'https://restcountries.eu/data/yem.svg', NULL, NULL),
(248, 'Zambia', 'ZMB', 'https://restcountries.eu/data/zmb.svg', NULL, NULL),
(249, 'Zimbabwe', 'ZWE', 'https://restcountries.eu/data/zwe.svg', NULL, NULL);

